   
                  (define a (string-length "b"))
                  (define b (string-length "c"))
                  (define c (string-length "d"))
                  (define d (string-ref "esadsad" 3))
                  (define e (string-ref "fsfdsaf3dfss" 10))
                  (define f (string-ref "g" 0))
                  (define g (string-length "dsfdsh"))
                  (define h (string-length "idfdsfds"))
                  (define i (string-length "jdsfdsf"))
                  (define j (string-length "kdsfdsf"))
                  (define k (string-length "lds"))
                  (define l (string-length "mdsff"))
                  (define m (string-length "nd"))
                  (define n (string-length ""))
                  (define o (string-length "pdsfdsf"))
                  (define p (string-ref "q34324dsfdsfdsf35r" 6))
                  (define q (string-ref "rdfsfdsf3rfdsfdsf" 8))
                  (define r (string-ref "sfddsfr4fdfdsfdsgfdgfdh" 14))
                  (define s (string-ref "tdfsdsf34sfddsf" 11))
                  (define t (string-ref "uffdsfds43sfdfds" 8))
                  (define u (string-ref "vdsfdsfdsf4dsfsdf" 9))
                  (define v (string-ref "wdsfdsfdsf3fsd" 6))
                  (define w (string-length "xff"))
                  (define x (string-length "dfsy"))
                  (define y (string-length "zdfs"))
                  (define z (string-length "asdfds"))

                  (eq? 'a z)
    