   
              (define x1 5)           
              (define x2 5)          
              (define x3 5)
              (define x4 5) 
              (define x5 5) 
              (define x6 5) 

              ; Checking applic tp with changed number of arguments
              (set! x1 (lambda () (x2 1)))           
              (set! x2 (lambda (y1) (x3 y1 2)))          
              (set! x3 (lambda (y1 y2) (x4 y1 y2 3)))
              (set! x4 (lambda (y1 y2 y3) (x5 y1 y2 y3 4))) 
              (set! x5 (lambda (y1 y2 y3 y4) (x6 y1 y2 y3 y4 5))) 
              (set! x6 (lambda (y1 y2 y3 y4 y5) `(,y1 ,y2 ,y3 ,y4 ,y5))) 

               (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
                 
    