   
           (define x1 5)           
              (define x2 5)          
              (define x3 5)
              (define x4 5) 
              (define x5 5) 
              (define x6 5) 

              ; Checking applic tp with changed number of arguments
              (set! x1 (lambda y0 (x2)))           
              (set! x2 (lambda y1 (x3 y1 2)))          
              (set! x3 (lambda y2 (x4 y2 3 4 5 6 7 8)))
              (set! x4 (lambda y3 (x5 y3 4 11 12 13 14 15 3 0 4 32 4 56 865 3 566 43 56674566 ))) 
              (set! x5 (lambda y4 (x6 y4 5))) 
              (set! x6 (lambda y5 `(,@y5))) 

              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)
              (x1)    
              (x1)
              (x1)      
    